import { Metadata } from 'next';
import Test from './Test';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function Page() {
  return <Test>hghgh</Test>;
}
